engines:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,controversial,design,naming,unusedcode,phpmd.xml"
    checks:
      Controversial/CamelCasePropertyName:
        enabled: true
      Controversial/CamelCaseMethodName:
        enabled: true
      CleanCode/StaticAccess:
        enabled: false
      CodeSize/TooManyMethods:
        enabled: true
        maxmethods: 25
      CodeSize/TooManyPublicMethods:
        enabled: true
        maxmethods: 25
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.php"
exclude_paths:
- .git/**/*
